### ISSUE TITLE
No JIRA issue found... yet jira issue is included

### ISSUE THREAD

**Issue by simpsonar77** [mohamicorp/yet-another-commit-checker#132]
I have configured the plugin to match valid JIRA issues, prevent unknown JIRA projects, and also enforce a Commit Message REGEX.  For a rececent push, I found that the commit was denied with NO JIRA issue found in commit message.  However, I ran the commit message through the REGEX(s) manually and found that the regex's matched.

Desired commit Message format:  [MYPROJNAME-1234] some other commit message, could be multiline, etc...

( I do not "care" about finding multiple JIRA issues as valid, just as long as one of them is valid, I will be happy)

Commit Message Regex:  ^\[([A-Z]+)-(\d+)\](.|\n)+

Require valid Jira Issues:  checked
Ignore Unknown JIRA Project Keys:  checked

Jql Matcher:  status=Assigned OR status="In Progress" OR status=Review

Error output:

remote: Pre-Commit Check - Server Side - ERROR!
remote: 
remote: refs/heads/XXXX/astyle: 60de6e3ccbc2e5ec15dbXXX076c9751421db42e: No JIRA Issue found in commit message.
remote: 
remote: End of error message
remote: 

The commit message in question:
*****************************************************
Author: Some Guy <some.guy@something.com>

    [MYPROJECT-725] Do Some Work
    
    Moved quite a bit of scattered functionality related to low level EOD
    channel control into XXX_XYZ, then modified stuff. There are a
    lot of lines of change, but most of it is just 1:1 translations of
    struct manipulation into function calls - in order to be sure all
    functionality was captured, the Command message was moved into
    XXX_XYZ and made inaccessible to the rest of the system, thus
    making it impossible to bypass the new functions.
**********************************************************

ideas?  going to test without having the JIRA Issue check enabled, but that's definitely not what I want.

**Comment by simpsonar77** [comment]
actually, I think the issue might be the use of groups in the commit message regex.  if I change:

^\[([A-Z]+)-(\d+)\](.|\n)+

to 

^(\[[A-Z]+-\d+\])(.|\n)+

Then the group is now ([PROJNAME-1234]) instead of [(PROJNAME)-(1234)].  Haven't tested yet, but does this sound right?

**Comment by sford** [comment]
Hi @simpsonar77 , yeah, that sounds correct. If a group exists in the commit message regex, only the [first group will be examined for JIRA issues](https://github.com/sford/yet-another-commit-checker#locating-issues-using-a-regex-group). This can be used to eliminate false positives by better targeting the JIRA issue.

You can either change the capturing group like in your example. Or, you can use non-capturing groups.

**Comment by szc001** [comment]
Hi, I love your add-on, but I have the same issue mentioned here... and my groups are correct:

(KYCP-\d+) [\w .!?\\-]{10,}[\w\s]*

This Regex, complains with issue not found (but it is there and in correct state) for this message:

KYCP-55 Export application button was not working. Fixed it in this change.

**Comment by sford** [comment]
@szc001 , I spot checked your regex and it appears to be fine. Maybe you can try [enabling debug logging](https://github.com/sford/yet-another-commit-checker#enable-logging) and trying again? That might help figure out why the commit is being rejected.

**Comment by szc001** [comment]
@sford I'm still debugging this, yet note that the `curl` command in your README seems to be incorrect... the URL should read `http://localhost:7990/rest/api/1.0/logs/logger/debug/com.isroot`

**Comment by Stefan-Z-Camilleri** [comment]
I've made some more headway on this... it looks like either YACC or BitBucket are sending the wrong AppLink UUIS to authenticate with Jira... in my case this is in the `atlassian-bitbucket.log`:

<img width="3840" alt="screen shot 2017-01-08 at 12 34 02" src="https://cloud.githubusercontent.com/assets/20099218/21749426/c80a1af2-d59e-11e6-9787-2856760bcd13.png">

Yet `42de01aa-6b09-3da6-82b1-3fe74748e2e5` is the UUID of Jira's applink in BitBucket, BitBucket's UUID in Jira is completely different.

If I send this request to Jira via postman, it in fact tells me:
<img width="1261" alt="screen shot 2017-01-08 at 12 35 54" src="https://cloud.githubusercontent.com/assets/20099218/21749440/02076c0a-d59f-11e6-9231-b25d45d16a46.png">

..which is correct, since that UUID only exists in BitBucket.

Sending it in with the correct UUID gives a good result.

So... need to figure out how to change the UUID being sent from BitBucket....

**Comment by sford** [comment]
Good progress! What version of BBS are you using and how many JIRA app
links do you have? Are other features like linkable JIRA issues working
(like when viewing commits in the BBS UI)?

If app links appear to be in an inconsistent state, one option might be to
remove app links and re-setup them up again.

**Comment by Stefan-Z-Camilleri** [comment]
I am using BitBucket 4.12.0
I have 1 app link to Jira 7.2.7
Linkable JIRA issues work fine, as does the JQL for merge hooks (another plugin).
I am using 2 legged OAuth (Impersonation) (I tried 3LO also)

I believe the difference is this:
- When using the UI, the links work using the logged in user... which is fine
- When you push changes over SSH, this is when things don't work... although the push is using the correct user account

I added a mod_rewrite rule on JIRA server to replace the UUID with the correct one... somehow this still fails, even though the rewrite is happening and pinging it over postman gives the correct result.

**Comment by sford** [comment]
YACC 1.2 has a limitation where it will only communicate with the primary application link (the only that is marked as `PRIMARY` in the application link list. This limitation is fixed in 1.2-SNAPSHOT. This might be a long shot but maybe there is another applink that is marked as primary but isn't being shown in the UI? This _might_ explain why YACC is choosing the one it is choosing.

Maybe you could poke around the database... on my BBS database, this appears to show my JIRA links:

```
select * from plugin_setting WHERE key_name LIKE 'applinks.%' AND key_value='jira';
```
or you could see if this shows anything interesting:
```
select * from plugin_setting WHERE key_name LIKE '%APP_LINK_ID_YACC_IS_TRYING_TO_USE%';
```

**Comment by Stefan-Z-Camilleri** [comment]
I am currently using YACC 1.11, which I believe is the latest.
I ran the queries below, and it returns 1 applink with the UUID of Jira on BitBucket.
Although I don't fully understand the relation, I updated the record temporarily with the UUID of BitBucket's applink in Jira.... unfortunately that still didn't work so I reverted it.

As an aside, when enabling debug logging as you described, I still don't see YACC debug messages.  I am currently unfamiliar with `atlas`, so is there something else I need to do to see YACC messages? Maybe run BitBucket with some special flags?

**Comment by justboutanything** [comment]
I am seeing a similar issue where the jira ticket is valid but i get no response in json.

2017-03-09 16:46:42,341 DEBUG [threadpool:thread-2] jenkins-svc @4QLC64x1006x4205x0 10wlgfo 10.0.35.250 SSH - git-receive-pack '/engprod/data-pipe' c.i.stash.plugin.YaccServiceImpl found jira issues [IssueKey{CM-933}] from commit message: CM-933 : Testing jira issue yacc
2017-03-09 16:46:42,345 DEBUG [threadpool:thread-2] jenkins-svc @4QLC64x1006x4205x0 10wlgfo  SSH - git-receive-pack '/engprod/data-pipe' c.i.s.plugin.jira.JiraServiceImpl number of JIRA application links: 1
2017-03-09 16:46:42,346 DEBUG [threadpool:thread-2] jenkins-svc @4QLC64x1006x4205x0 10wlgfo  SSH - git-receive-pack '/engprod/data-pipe' c.i.s.plugin.jira.JiraServiceImpl executing JQL query on JIRA application link 'Jira': issueKey=CM-933
2017-03-09 16:46:42,397 DEBUG [threadpool:thread-2] jenkins-svc @4QLC64x1006x4205x0 10wlgfo SSH - git-receive-pack '/engprod/data-pipe' c.i.s.plugin.jira.JiraServiceImpl json response: {"startAt":0,"maxResults":50,"total":0,"issues":[]}
2017-03-09 16:46:42,398 DEBUG [threadpool:thread-2] jenkins-svc @4QLC64x1006x4205x0 10wlgfo SSH - git-receive-pack '/engprod/data-pipe' c.i.s.plugin.errors.YaccErrorBuilder error type=ISSUE_JQL message=refs/heads/develop: 4a6cc26d61994a2c70931a41cba8f5aaeadf9bb5: CM-933: JIRA Issue does not exist
Is there any setting I need to change on jira side ?

**Comment by sford** [comment]
@justboutanything Thanks for including debug logs!

According to the logs, it executed a JIRA JQL search `issueKey=CM-933` and JIRA returned no results. This is helpful because it indicates that YACC is more or less working, but just that JIRA didn't return the issue.

I would spot check JIRA and execute that same query on your instance and verify that ticket is returned. I would also double check that the Application Link in BBS looks correct (like it is communicating with the right JIRA instance). I would also make sure the user doing the push has permissions to see that issue... JQL searches won't return issues that the user doesn't have permissions to see.

**Comment by justboutanything** [comment]
Thank you for your prompt response.

So I tried this same jira ticket with disabling the YACC and it goes through fine and also updates the jira link with the commit. So I know that the Jira (that is in Application link in BBS is correct) is getting updated when I commit something to bitbucket.
I just feel that YACC to jira communication is not happening ?
I do not have admin permissions on the jira side as I need to work with another team for that. Is there anything I can ask the jira admin to check to see if he sees anything from YACC ?

**Comment by sford** [comment]
> I just feel that YACC to jira communication is not happening ?

It should be communicating with JIRA fine because it got the following response from JIRA:

```
{"startAt":0,"maxResults":50,"total":0,"issues":[]}
```

This is the expected JSON response from JIRA if JQL doesn't return anything.

If the issue really exists and JQL `issueKey=CM-933` works when you manually test it, then this _feels_ like a permission issue, because if the user doesn't have permission to view it, you would see empty results and YACC complaining it can't find the issue.

In a typical setup, communication looks like:

```
browser <--\        browser <--\
           |                   |
git <----> BBS <-- oauth --> JIRA
```

As per your comments, you manually verified and tested BBS and JIRA when logging into them in a browser. I would also spot check that the expected users are being used when git connects to BBS, and also the BBS<->JIRA communication which should probably be using oauth. If it isn't using oauth, that might also explain what is going on, because it might be using a user other than the one you expect when communicating with JIRA.

**Comment by justboutanything** [comment]
Thank you for your response. I configured OAuth on both sides and it was not able to authenticate. So I changed the configuration to OAuth (impersonation) and that worked.

**Comment by mailming** [comment]
I saw the same issue in my company bitbucket app:

if we set a regex pattern in 
Commit Message Regex
and then have Require valid Jira Issues: checked

Bitbucket will show: No JIRA Issue found in commit message. with rejection

However, if I remove Commit Message Regex in pattern box, then jira issue will pass accepting new commits.

I hope this is a bug not a feature.

**Comment by AlexanderAmelkin** [comment]
@sford, It would be very helpful if YACC had a separate regex just for JIRA issue matching. Or a checkbox to disable regex group searching. Or a setting that specifies the number of the group to check for the issue.

Regex groups may be used for many different purposes, and it may (and does for me) happen that the first group is not about JIRA issue matching.

For example this regexp aimed at enforcing Linux Kernel 55/70 commit log style fails to find a JIRA issue:

[\p{Print}]{10,55}(\n\p{Print}{0,70})*\nJIRA: ([A-Z]+-[0-9]+)

It even fails if I do it this way and include an issue key in one of the lines matched by the first group:

[\p{Print}]{10,55}(\n\p{Print}{0,70})*

**Comment by sford** [comment]
Hi @AlexanderAmelkin ,

Can you try using a non capturing group? For example, something like:

```
... (?: ... ) ... ([A-Z]+-[0-9]+)
```

JIRA extraction will check the first captured group if it exists, but non capturing groups should be able to be used if grouping is needed without capture.
