### ISSUE TITLE
yacc push failed due to 'process timed out'

### ISSUE THREAD

**Issue by bhchew** [mohamicorp/yet-another-commit-checker#141]
we are getting such errors intermittently while trying to git push

```
remote: Hook com.isroot.stash.plugin.YaccHook failed. Error:
remote: An error occurred while executing an external process: process timed out
```

What can likely cause this?

**Comment by sford** [comment]
It specifically mentions an external process... YACC (using BBS APIs) will fork out to git for a couple things. Maybe there is a problem with that? What versions of YACC, BBS, and git are you using?

**Comment by markottaviani** [comment]
We're seeing this error intermittently with a CI Job that pushes via SSH.

Issue started once we upgraded to 
Bitbucket DataCenter 4.13.0
Git 2.11.0
Yacc 1.13

Tried enabling the **Exclude Service User Commits** option, but still seeing the same thing.

**Comment by sford** [comment]
I can think of a couple things that might cause this:

* High I/O on BBS host causing git operations to be slow
* Unreliable connection to JIRA causing BBS<->JIRA requests to be slow and/or timeout

To help figure this out, is it possible to rule any of these out? Is there anything interesting in the BBS logs that might point out what is happening?

**Comment by markottaviani** [comment]
High I/O slowing down git operations is very much a possibility.  I think the network infrastructure is getting a bit overwhelmed at times (we're planning some upgrades, and we're coping with some 15-20 ms database latency).  Additionally the repo in question was getting a tag and a small commit added to it non-stop every 2-3 minutes throughout the day, everyday.  

The team who had the job changed how it works a day or two after I reported the issue, and recreated the repo.   We haven't had any of our 700+ users report any issues with YACC since scrapping that repo, also I'm told nothing turned up in the BBS logs.  

We don't use JIRA at all.

If it shows up again or any other details emerge I'll let you know.

**Comment by sford** [comment]
@markottaviani Cool, thanks for the update!
