### ISSUE TITLE
YACC not interacting with Repository Templates for Bitbucket

### ISSUE THREAD

**Issue by npoisson** [mohamicorp/yet-another-commit-checker#162]
Hi,

We use both YACC and Repository Templates for Bitbucket plugins to facilitate creation of new repos with standard settings, but for some reason when we assign a template to a project/repository, the YACC configuration is never replicated. We have done this 30-40 times at this point and the behavior is always observed. YACC is the only plugin we use which never gets its config replicated.

Are you aware of any hooks that need to be programmed on your side in order to be compatible with the Repository Templates for Bitbucket plugin?

Regards,
Nick

**Comment by sford** [comment]
Hi @npoisson , 

I have not used that plugin and don't really know anything about it, so not sure what could be going on.

**Comment by npoisson** [comment]
I have managed to get my hands on the server logs and am becoming convinced this is more an issue with the other plugin. The error given during the replication mentions an invalid JQL query.

2017-07-14 09:07:02,273 ERROR [Caesium-1-1]  c.m.s.t.reposettings.ops.RepoHooksOp REPOTEMPLATES: failed to enable template hook com.isroot.stash.plugin.yacc:yaccHook
2017-07-14 09:07:02,273 ERROR [Caesium-1-1]  c.m.s.t.reposettings.ops.RepoHooksOp REPOTEMPLATES: field errors: issueJqlMatcher = [JQL Query is invalid.] 

When creating the yacc configs, these queries are fine and execute properly on a number of JIRA projects.  But when replicating these configs through the Repository Templates plugin, the integration somehow no longer thinks these are valid. 

The simplest I've managed to make work is 'assignee is not EMPTY'. But if I do something more complex like 'assignee is not EMPTY and status = "In Progress"' the yacc config is not activated and the logs shows the JQL error, as if it was trying to validate against a project that does not have the "In Progress" status. I've tried several statuses, and lower/upper case combinations.

I don't know if this could ring a bell on your end or if it's more of a Repository Templates issue, but if you have any relevant insights I could give them that would be appreciated.

Regards,
Nick

**Comment by sford** [comment]
Hi Nick,

Thanks for digging on this a little deeper! Appreciate it. 

I think you narrowed down this issue pretty well. One potential problem could involve authentication. When YACC settings that include a JQL query is saved, it is validated by trying to execute the JQL query on your JIRA instance that is configured in a BBS Application Link. This request must be authenticated, and it is possible that authentication could be a little different between when you are saving YACC settings yourself, and when that plugin is doing it on your behalf.

There could also be an encoding problem. For example, if that plugin is changing `"` to `&quot;` (just an example) it could explain why one query works (`assignee is not EMPTY`) but not the other (`assignee is not EMPTY and status = "In Progress"`). You can test this theory by trying a status query that doesn't use quotes... like `assignee is not empty and status = open`.

You could also try [enabling YACC debug logging](https://github.com/sford/yet-another-commit-checker#enable-logging)... YACC will log the JQL queries it is trying to run. Using this logging, you could determine whether or not the JQL query is getting corrupted due to an encoding issue.

**Comment by george-vulov** [comment]
The next YACC release will include [JIRA user impersonation](https://mohamicorp.atlassian.net/browse/YACC-3), whereby a single globally-configured user will always be used to authenticate against Jira for the purposes of verifying JQL. Configuring this feature may address the authentication issues you're seeing during repository cloning.

**Comment by george-vulov** [comment]
Jira user impersonation is now released, in [version 2.0.0](https://marketplace.atlassian.com/apps/1211854/yet-another-commit-checker?hosting=server&tab=versions)
