### ISSUE TITLE
YACC at the Global level - private repos and forked repos

### ISSUE THREAD

**Issue by bhushan154** [mohamicorp/yet-another-commit-checker#188]
If enabling YACC at the global level, would it also be applied to private and forked repositories?

Are there any tips to manage this at scale on large instances? 1000 of repositories where we need to apply yacc only on certain projects.

**Comment by george-vulov** [comment]
If you enable YACC on a global level, it will apply to all repositories, including private repos and forks. You have two options
1. Enable YACC globally, then explicitly turn off YACC on repositories where it's not desired. You can do this by enabling YACC on the repository level, but without any policies to enforce.
2. Enable YACC at the project level (not the repository level) where it's required. This will not affect private repositories and forks, since private repositories aren't considered members of the project.

You can automate the process of enabling or disabling YACC for various projects & repositories by using the REST API to enable/disable the hook.

**Comment by george-vulov** [comment]
Here's the relevant documentation page for using the REST API: [How to modify YACC settings programmatically](https://mohamicorp.atlassian.net/wiki/spaces/DOC/pages/1484652654/How+to+modify+YACC+settings+programmatically).
