### ISSUE TITLE
Only working for Admin users

### ISSUE THREAD

**Issue by mandresen10** [mohamicorp/yet-another-commit-checker#204]
This was working great for me, but when I rolled it out to our team only Bitbucket Admins were able to use it.  Other users were receiving errors as shown in the attachment.
![push_rejected](https://user-images.githubusercontent.com/43865012/49763888-82398580-fc93-11e8-96c9-bb0eed6952d9.png)

They followed the directions regarding linking their Stash account to their Jira account but it still failed.

Any thoughts?

Thanks.

**Comment by sford** [comment]
Hi @mandresen10 ,

What happens if these users try using the built-in JIRA integration that BBS has to offer? For example, hovering over JIRA issues in PR titles or in commit lists? 

YACC just uses the existing BBS<->JIRA Application Link and OAuth tokens. So, I would first verify that is working. Typically the first time a BBS user tries to do something that triggers JIRA integration, BBS will deal with the OAuth authentication process. Normally this is already in place... YACC tries to be friendly and give a link to do it, but I would still try to make sure this is working first outside of YACC.
