### ISSUE TITLE
 Illegal character in query

### ISSUE THREAD

**Issue by petranzoom** [mohamicorp/yet-another-commit-checker#75]
I have problem with pushing code from sourcetree or git to one branch. Push produce this error message 
remote: Hook com.isroot.stash.plugin.YaccHook failed. Error:
remote: Illegal character in query at index 64: http://jira:81/rest/api/2/project/ENC?xoauth_requestor_id=Access key user (Ivan.Rogic@zoomint.com)
To ssh://git@stash:799/six/applications.git
! [remote rejected] ..
<img width="509" alt="screen shot 2015-09-11 at 12 25 37 pm" src="https://cloud.githubusercontent.com/assets/14329431/9931597/53d99890-5d3d-11e5-81eb-15c7d5383640.png">
<img width="586" alt="screen shot 2015-09-10 at 5 03 45 pm" src="https://cloud.githubusercontent.com/assets/14329431/9931599/570f7b24-5d3d-11e5-912b-a367ff200f85.png">

**Comment by sford** [comment]
Hi @petranzoom,

That URL looks a little strange, index 64 is the space after 'Access' in 'Access Key', so something is wrong with that URL since you can't have spaces in it. And I am not sure access key users should be using oauth (since it appears to be oauth related due to 'xoauth'.

Is OAuth working fine in your Stash install? Like, can you click JIRA issues and have it communicate with Stash correctly? Was YACC working before, or is this your first time using it? Does it affect just one user or are there some users (maybe non access key?) that it is working for?

**Comment by petranzoom** [comment]
It is problem only of one user. He worked well with ssh keys. we don't do any of changes on server or client , but push make this problem. We have workaround. He switch from ssh to https and everithink is working.
